[build]
  command = "pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.0"
  
[[plugins]]
  package = "@netlify/plugin-functions-core"
  [plugins.inputs]
    NODE_ENV = "production"
